language: python
python:
  - "3.5"
install:
  - "pip install tox"
script:
  - "tox -v -e py35"
notifications:
  email: false
  # This is Colin's instance of Homu, in the future
  # we'll move this to a production cluster.
  webhooks: http://escher.verbum.org:54856/travis
