language: python
python:
  - "2.6"
#  - "3.3"
install:
  - "pip install -r requirements.txt"
  - "pip install -r test-requirements.txt"
script:
  - "pep8 -r src/"
  - "nosetests -v --with-coverage --cover-package commissaire --cover-min-percentage 80 test/"
notifications:
  email: false
